---

- name: create temporary directory
  tempfile:
    state: directory
    suffix: DockerTEMP
  register: dockertempdir

- template:
    src: "{{item}}"
    dest: "{{ dockertempdir.path }}/{{(item | splitext)[0]}}"
  with_items:
    - "Dockerfile.j2"
    - "ks_ubuntu1804.cfg.j2"
    - "ubuntu1804.json.j2"

- copy:
    content: "{{ lookup('vars', item) }}"
    dest: "{{ dockertempdir.path }}/{{item}}"
  with_items:
    - "id_rsa_esxisvc_nopw"
    - "id_rsa_shutdown_nopw"

- copy:
    src: "{{item}}"
    dest: "{{ dockertempdir.path }}/{{item}}"
  with_items:
    - "{{packer_pkg_url | basename}}"
    - "{{ubuntu_iso.url | basename}}"
  when: copylocal is defined and copylocal|bool

- name: Do it with Docker
  block:
  - name: Build Docker image
    docker_image:
      source: build
      build:
        pull: yes
        path: "{{ dockertempdir.path }}"
      force_source: true
      name: ubuntu1804

  - name: Remove image
    docker_image:
      name: ubuntu1804
      state: absent
  when: skip_docker is not defined and not skip_docker|bool

- name: Do it without Docker
  command: "{{item}}"
  args:
    chdir: "{{ dockertempdir.path }}"
  with_items:
    - "unzip {{packer_pkg_url | basename}}"
    - "./packer build ./{{packerfile_fname}}"
  when: skip_docker is defined and skip_docker|bool

- name: Remove temporary directory
  file:
    path: "{{ dockertempdir.path }}"
    state: absent
