---

- name: create temporary directory
  tempfile:
    state: directory
    suffix: DockerTEMP
  register: dockertempdir

- copy:
    content: "{{ esxi.private_key }}"
    dest: "{{ dockertempdir.path }}/esxi_private_key"
    mode: '0600'

- openssh_keypair:
    path: "{{ dockertempdir.path }}/id_rsa_shutdown"
  register: shutdown_keypair

- template:
    src: "{{item}}"
    dest: "{{ dockertempdir.path }}/{{(item | basename | splitext)[0]}}"
  with_items:
    - "Dockerfile.j2"
    - "packer/{{packerfile_fname}}.j2"
    - "kickstart/{{kickstartfile_fname}}.j2"


- copy:
    src: "{{item}}"
    dest: "{{ dockertempdir.path }}/{{item}}"
  with_items:
    - "{{packer_pkg_url | basename}}"
    - "{{base_os.iso_url | basename}}"
  when: copylocal is defined and copylocal|bool

- block:
  - name: Packer build within Docker
    docker_image:
      source: build
      build:
        pull: yes
        path: "{{ dockertempdir.path }}"
      force_source: true
      name: "{{packer_info.img_name}}"

  - name: Remove image
    docker_image:
      name: "{{packer_info.img_name}}"
      state: absent
  when: skip_docker is not defined or not skip_docker|bool

- name: Packer build without Docker
  command: "{{item}}"
  args:
    chdir: "{{ dockertempdir.path }}"
  with_items:
    - "unzip {{packer_pkg_url | basename}}"
    - "./packer build -on-error=abort ./{{packerfile_fname}}"
  when: skip_docker is defined and skip_docker|bool

- name: Remove temporary directory
  file:
    path: "{{ dockertempdir.path }}"
    state: absent
