---

userinfo:
  - name: root
    lock_passwd: false
    hashed_passwd: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33333333333333333333333333333333333333333333333
    ssh_authorized_keys: ['ssh-rsa 33333333333333333333333333333333333333333333333']
#  - name: ansible
#    ssh_authorized_keys: ['ssh-rsa 33333333333333333333333333333333333333333333333']
#    sudo: "ALL=(ALL) NOPASSWD:ALL"
#    groups: "admin"
#    passwd: "*"
#    lock_passwd: false
#    shell: /bin/bash

base_os:
  ubuntu1804:
    name: "ubuntu1804"
    iso_url: "http://cdimage.ubuntu.com/releases/18.04.4/release/ubuntu-18.04.4-server-amd64.iso"
    iso_checksum: "sha256:e2ecdace33c939527cbc9e8d23576381c493b071107207d2040af72595f8990b"     # http://cdimage.ubuntu.com/releases/18.04.4/release/SHA256SUMS
  ubuntu2004_legacy:
    name: "ubuntu2004l"
    iso_url: "http://cdimage.ubuntu.com/cdimage/ubuntu-legacy-server/releases/20.04/release/ubuntu-20.04.1-legacy-server-amd64.iso"
    iso_checksum: "none"
  ubuntu2004:
    name: "ubuntu2004"
    iso_url: "https://releases.ubuntu.com/20.04/ubuntu-20.04.4-live-server-amd64.iso"
    iso_checksum: "none"
  ubuntu2204:
    name: "ubuntu2204"
    iso_url: "https://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso"
    iso_checksum: "none"


packer_pkg_url: "https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip"

image_config:
  disk_size_mb: "12288"
  memory_mb: "2048"
  cpus: "2"
  swapfile_mb: 0
  remove_snapd: yes
  systemd_debug: no     # Whether to debug systemd
  esxi:
    host: "192.168.1.30"
    username: "root"
    password: !vault |-
      $ANSIBLE_VAULT;1.1;AES256
      33333333333333333333333333333333333333333333333
    datastore: "vdisks"
    ethernet0_networkName: "VM Network"
    # ethernet0_macAddress: "00:0c:29:f2:dc:da"
    firmware: "efi"
    hw_version: 19
  libvirt:
    host: "192.168.1.3"
    username: "svc"
    private_key: !vault |-
      $ANSIBLE_VAULT;1.1;AES256
      33333333333333333333333333333333333333333333333
    firmware: "/usr/share/ovmf/OVMF.fd"
    fileformat: "qcow2"
    storage_pool: "/media/vdisks"
  xcp_ng:
    host: "192.168.1.71"
    username: "root"
    password: !vault |-
      $ANSIBLE_VAULT;1.1;AES256
      33333333333333333333333333333333333333333333333
    sr_name: "84gb-nvme"
    sr_iso_name: "LocalISO"
    firmware: "bios"
    network_names: "Network0"
    platform_args: {viridian: 'false', nx: 'true', pae: 'true', apic: 'true', timeoffset: '0', acpi: '1', cores-per-socket: '1'}
