FROM ubuntu:22.04

ENV PACKER_LOG=1
ENV PACKER_LOG_PATH="./packerlog.txt"

{#Faster version - copies from local instead of downloads.#}
{% if uselocal is defined and uselocal %}

COPY {{cloud_type}}__{{os_id}}/* /{{cloud_type}}__{{os_id}}/
COPY {{base_os[os_id].iso_url | basename}} {{packer_pkg_url | basename}} /
RUN apt-get update; apt-get -y install unzip \
    && unzip {{packer_pkg_url | basename}} \
    && ./packer plugins install {{plugin}}
CMD ["./packer", "build", "-on-error=abort", "{{cloud_type}}__{{os_id}}/packer.json"]

{%  else %}

COPY {{cloud_type}}__{{os_id}}/* /{{cloud_type}}__{{os_id}}/
RUN  apt-get update; apt-get -y install unzip wget \
  && wget {{base_os[os_id].iso_url}} \
  && wget {{packer_pkg_url}} \
  && unzip {{packer_pkg_url | basename}} \
  && ./packer plugins install {{plugin}}
CMD ["./packer", "build", "-on-error=abort", "{{cloud_type}}__{{os_id}}/packer.json"]

{% endif %}