FROM ubuntu:18.04

{#Faster version - copies from local instead of downloads.#}
{% if  copylocal is defined and copylocal %}

COPY {{os_id}}/* /{{os_id}}/
COPY {{base_os[os_id].iso_url | basename}} {{packer_info.pkg_url | basename}} /
RUN apt-get update; \
    apt-get -y install unzip && \
    unzip {{packer_info.pkg_url | basename}}
CMD ["./packer", "build", "-on-error=abort", "{{os_id}}/packer.json"]

{%  else %}

COPY {{os_id}}/* /{{os_id}}/
RUN  apt-get update; apt-get -y install unzip wget \
  && wget {{base_os[os_id].iso_url}} \
  && wget {{packer_info.pkg_url}} \
  && unzip {{packer_info.pkg_url | basename}}

CMD ["./packer", "build", "-on-error=abort", "{{os_id}}/packer.json"]

{% endif %}