FROM ubuntu:18.04

{% if  copylocal is defined and copylocal %}

##Faster version - copies from local instead of downloads.
COPY {{packerfile_fname}} {{kickstartfile_fname}} id_rsa_shutdown esxi_private_key {{base_os.iso_url | basename}} {{packer_pkg_url | basename}} /goldimg/
RUN cd goldimg \
  && apt-get update; apt-get -y install unzip \
  && unzip {{packer_pkg_url | basename}} \
  && ./packer build ./{{packerfile_fname}}

{%  else %}

COPY {{packerfile_fname}} {{kickstartfile_fname}} id_rsa_shutdown esxi_private_key /goldimg/
RUN  cd goldimg \
  && apt-get update; apt-get -y install unzip wget \
  && wget {{base_os.iso_url}} \
  && wget {{packer_pkg_url}} \
  && unzip {{packer_pkg_url | basename}} \
  && ./packer build ./{{packerfile_fname}}

{% endif %}